# Site settings
title: Alexander Volfovsky
email: alexander.volfovsky@duke.edu
description: > # this means to ignore newlines until "baseurl:"
  assistant professor of statistical science and computer science at duke university
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://volfovsky.github.io" # the base hostname & protocol for your site
twitter_username: alex_volfovsky
instagram_username: mordytheschnootzface
github_username:  volfovsky
arxiv_url: "https://arxiv.org/abs"
#author:
#  orcid: 0000-0003-4462-1020

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

google_analytics: UA-57660811-2 

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
